site_name: Sparrowpit Methodist Church
theme:
  name: material
nav:
  - Home: index.md
  - History: history.md
  - Traditions: traditions.md
  - Find Us: find.md
  - Pictures of Sparrowpit: pictures.md 
  - MkDocs: mkdocs.md

markdown_extensions:
  - attr_list
  - md_in_html
